export const productResource = (product: any) => {
  if (!product) return product;
  return {
    id: product.id,
    shopId: product.shopId,
    categoryId: product.categoryId,
    sourceId: product.sourceId,
    name: product.name,
    sku: product.sku,
    brand: product.brand,
    model: product.model,
    variant: product.variant,
    color: product.color,
    storage: product.storage,
    ram: product.ram,
    condition: product.condition,
    purchasePrice: product.purchasePrice,
    salePrice: product.salePrice ?? product.expectedSalePrice,
    compareAtPrice: product.compareAtPrice,
    minimumSalePrice: product.minimumSalePrice,
    quantity: product.quantity,
    soldQuantity: product.soldQuantity,
    availableQuantity: product.availableQuantity,
    imei1: product.imei1,
    imei2: product.imei2,
    serialNumber: product.serialNumber,
    barcode: product.barcode,
    qrCode: product.qrCode,
    warrantyType: product.warrantyType,
    warrantyMonths: product.warrantyMonths,
    onlineSaleEnabled: product.onlineSaleEnabled,
    offlineSaleEnabled: product.offlineSaleEnabled,
    saleMode: product.saleMode,
    marketplaceStatus: product.marketplaceStatus,
    status: product.status,
    discountType: product.discountType,
    discountValue: product.discountValue,
    lowStockAlert: product.lowStockAlert,
    useShopDefaultTax: product.useShopDefaultTax,
    customTaxPercentage: product.customTaxPercentage,
    serialNumberRequired: product.serialNumberRequired,
    imeiRequired: product.imeiRequired,
    description: product.description,
    purchaseDate: product.purchaseDate,
    images: product.images,
    category: product.category,
    source: product.source,
    shop: product.shop,
    createdAt: product.createdAt,
    updatedAt: product.updatedAt,
  };
};

export const productCollection = (items: any[]) => items.map(productResource);
